### Obtener todos los estudiantes
GET http://127.0.0.1:8000/api/estudiantes
Accept: application/json

### Agregar un nuevo estudiante
POST http://127.0.0.1:8000/api/estudiantes
Content-Type: application/json

{
    "cod": "12345",
    "nombres": "Juan Perez",
    "email": "juan.perez@example.com",
    "nota_definitiva": 4.5,
    "estado": "Aprobado"
}

### Eliminar un estudiante
DELETE http://127.0.0.1:8000/api/estudiantes/12345
Accept: application/json